FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-runtime

RUN apt-get update 
RUN apt-get install -y \
        ffmpeg \
        nano \
        curl \
        espeak-ng \
        libpq-dev \
        build-essential \
        telnet

RUN pip install --upgrade pip
# RUN pip install -U --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

WORKDIR /app
COPY requirements.txt /app/requirements.txt
COPY requirements_serving.txt /app/requirements_serving.txt
COPY requirements_ui.txt /app/requirements_ui.txt

RUN python3.11 -m pip uninstall -y numpy
RUN python3.11 -m pip --no-cache-dir install -r /app/requirements.txt
RUN python3.11 -m pip --no-cache-dir install -r /app/requirements_serving.txt
RUN python3.11 -m pip --no-cache-dir install -r /app/requirements_ui.txt

RUN mkdir -p /app/weights

COPY ./weights /app/weights
COPY ./src /app

# CMD ["python3.11", "controller.py"]

# docker build -t dixuson/mmv --load --rm -f Dockerfile_controller .
# docker run --gpus all -d -p 8386:8386 -p 8385:8385 --name mvvtv dixuson/mmv